In [138]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from dipy.core.sphere import disperse_charges, HemiSphere, Sphere
from dipy.direction import peak_directions
from dipy.core.gradients import gradient_table
from dipy.data import get_sphere
from dipy.sims.voxel import multi_tensor, multi_tensor_odf, single_tensor
from mpl_toolkits.mplot3d import Axes3D
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
import nibabel as nib
import random
import math

In [139]:
thetas = list(np.load("synthetic_data/thetas.npy"))
phis = list(np.load("synthetic_data/phis.npy"))

hemisphere = HemiSphere(theta=thetas, phi=phis) # We already dispersed charges when building the hemisphere in dipy_test
sphere = Sphere(xyz=np.vstack((hemisphere.vertices, -hemisphere.vertices)))


def detect_peaks(F, relative_peak_threshold, min_separation_angle):
    peak_format = np.zeros((len(F), 42))
    max_peak_count = 0
    for i, sample in enumerate(F):
        # Duplicate the sample for both hemispheres
        F_sphere = np.hstack((sample, sample)) / 2
        # Find peak directions
        directions, values, indices = peak_directions(F_sphere, sphere, relative_peak_threshold, min_separation_angle)
        directions = sample[indices][:, np.newaxis] * directions # multiplying with fractions
        directions_flattened = directions.flatten()
        peak_format[i][0:len(directions_flattened)] = directions_flattened
        if len(directions_flattened) / 3 > max_peak_count:
            max_peak_count = len(directions_flattened) / 3
    return peak_format, max_peak_count

In [140]:
class MatrixFactorizationBatchNormalizationNet(nn.Module):
    def __init__(self, input_size, hidden_sizes, output_size):
        super(MatrixFactorizationBatchNormalizationNet, self).__init__()
        # Define the network layers
        self.fc1 = nn.Linear(input_size, hidden_sizes[0])
        self.bn1 = nn.BatchNorm1d(hidden_sizes[0])
        self.fc2 = nn.Linear(hidden_sizes[0], hidden_sizes[1])
        self.bn2 = nn.BatchNorm1d(hidden_sizes[1])
        self.fc3 = nn.Linear(hidden_sizes[1], hidden_sizes[2])
        self.bn3 = nn.BatchNorm1d(hidden_sizes[2])
        self.fc4 = nn.Linear(hidden_sizes[2], output_size)
        self.softplus = nn.Softplus()

    def forward(self, x):
        x = torch.relu(self.bn1(self.fc1(x)))
        x = torch.relu(self.bn2(self.fc2(x)))
        x = torch.relu(self.bn3(self.fc3(x)))
        x = self.softplus(self.fc4(x))  # Softplus activation for the output layer
        return x

In [141]:
class MatrixFactorizationNet(nn.Module):
    def __init__(self, input_size, hidden_sizes, output_size):
        super(MatrixFactorizationNet, self).__init__()
        # Define the network layers
        self.fc1 = nn.Linear(input_size, hidden_sizes[0])
        self.fc2 = nn.Linear(hidden_sizes[0], hidden_sizes[1])
        self.fc3 = nn.Linear(hidden_sizes[1], hidden_sizes[2])
        self.fc4 = nn.Linear(hidden_sizes[2], output_size)
        self.softplus = nn.Softplus()

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = self.softplus(self.fc4(x))  # Softplus activation for the output layer
        return x

class MatrixDataset(Dataset):
    def __init__(self, S, F):
        self.S = S
        self.F = F

    def __len__(self):
        return len(self.S)

    def __getitem__(self, idx):
        return self.S[idx], self.F[idx]
    
def apply_sparsity(F, sparsity_threshold=0.9):
    max_value, _ = F.max(dim = 1, keepdim = True)
    F[F < 0.1 * max_value] = 0
    return F


S = np.load("synthetic_data/uniform_5e5/S.npy")
F = np.load("synthetic_data/uniform_5e5/F.npy")
print(np.shape(S))
print(np.shape(F))

# Convert them to PyTorch tensors
S = torch.from_numpy(S).float()
# Separate into training and testing set
split = 0.9
num_entries = len(S)
train_len = int(num_entries * split)

S_train = S[:train_len]
F_train = F[:train_len]

S_test = S[train_len:]
F_test = F[train_len:]
batch_size = 1024

criterion = nn.MSELoss()

train_dataset = MatrixDataset(S_train, F_train)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = MatrixDataset(S_test, F_test)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

N_test, _ = np.shape(S_test)
N, n_b = np.shape(S_train)
_, n = np.shape(F_train)

input_size = n_b
output_size = n

net = MatrixFactorizationBatchNormalizationNet(input_size, [512, 256, 128], output_size)
net.load_state_dict(torch.load("trained_model/512_256_128_BN_uniform_diff_snrs_6e5_lr_0.001.pt", map_location=torch.device('cpu')))

(500000, 65)
(500000, 180)


<All keys matched successfully>

In [142]:
mask = nib.load('real_data/mask.nii').get_fdata().astype(bool)
white_mask = nib.load('real_data/white_matter_mask.nii').get_fdata().astype(bool)

hardi_snr10 = nib.load('real_data/DWIS_hardi-scheme_SNR-10.nii').get_fdata()
hardi_snr20 = nib.load('real_data/DWIS_hardi-scheme_SNR-20.nii').get_fdata()
hardi_snr30 = nib.load('real_data/DWIS_hardi-scheme_SNR-30.nii').get_fdata()

hardi_snr10_masked = hardi_snr10[mask]
hardi_snr20_masked = hardi_snr20[mask]
hardi_snr30_masked = hardi_snr30[mask]
hardi_snr10_masked *= (100/hardi_snr10_masked[0][0])
hardi_snr20_masked *= (100/hardi_snr20_masked[0][0])
hardi_snr30_masked *= (100/hardi_snr30_masked[0][0])

hardi_snr10_white_masked = hardi_snr10[white_mask]
hardi_snr20_white_masked = hardi_snr20[white_mask]
hardi_snr30_white_masked = hardi_snr30[white_mask]
hardi_snr10_white_masked *= (100/hardi_snr10_white_masked[0][0])
hardi_snr20_white_masked *= (100/hardi_snr20_white_masked[0][0])
hardi_snr30_white_masked *= (100/hardi_snr30_white_masked[0][0])

gt_white_masked = pd.read_pickle("real_data/ground_truth_peaks_white_masked.pkl")

In [143]:
test_set_hardi = torch.from_numpy(hardi_snr30_white_masked).float()
F_test_set_hardi = torch.from_numpy(np.zeros(hardi_snr30_white_masked.shape[0])).float()
test_dataset_hardi = MatrixDataset(test_set_hardi, F_test_set_hardi)
test_loader_hardi = DataLoader(test_dataset_hardi, batch_size=batch_size, shuffle=False)

In [144]:
net.eval()
with torch.no_grad():
    total_loss = 0.0
    F_pred_matrix_normalized_list = []

    for S_batch, F_batch in test_loader_hardi:
        S_batch_flattened = S_batch.to_dense().view(S_batch.size(0), -1)

        F_batch_pred = net(S_batch_flattened)
        F_batch_pred = apply_sparsity(F_batch_pred)
        F_batch_pred_normalized = F_batch_pred / (F_batch_pred.sum(dim=1, keepdim=True) + 1e8)

        #loss = criterion(F_batch_pred_normalized, F_batch)

        #total_loss += loss.item()
        F_pred_matrix_normalized_list.append(F_batch_pred_normalized)

    # Calculate the average loss over all test samples
    avg_loss = total_loss / len(test_loader)
    print("Average Test Loss:", avg_loss)


Average Test Loss: 0.0


In [145]:
F_pred_np = np.concatenate([tensor.cpu().numpy().flatten() for tensor in F_pred_matrix_normalized_list])
F_pred_np = F_pred_np.reshape((-1,180)).astype(np.double)

In [146]:
relative_peak_threshold = 0.1
min_separation_angle = 25

peak_format, peak_count = detect_peaks(F_pred_np, relative_peak_threshold, min_separation_angle)

In [147]:
pd.to_pickle(peak_format, "trained_model/512_256_128_BN_uniform_diff_snrs_6e5_lr_0.001.pkl")

In [148]:
angle_pairs = pd.read_pickle("synthetic_data/angle_pairs.pkl")
evals = np.tile([0.0017, 0.0002, 0.0002], (len(angle_pairs), 1))

In [149]:
def cartesian_to_spherical(x, y, z):
    # Calculate phi (azimuthal angle)
    phi = math.atan2(y, x)
    
    # Calculate theta (polar angle)
    r_xy = math.sqrt(x**2 + y**2)
    theta = math.atan2(r_xy, z)
    
    # Convert angles to degrees
    phi_deg = math.degrees(phi)
    theta_deg = math.degrees(theta)
    
    return phi_deg,theta_deg

In [150]:
def angles_fractions(gt):
    angles = []
    fractions = []
    for i in range(len(gt)//3):
        if gt[3*i] != 0.0:
            phi, theta = cartesian_to_spherical(gt[3*i], gt[3*i+1], gt[3*i+2])
            angles.append((theta, phi))
            fractions.append(gt[3*i]**2 + gt[3*i+1]**2 + gt[3*i+2]**2)
    fractions = fractions / sum(fractions)
    return angles, fractions


In [151]:
sphere2 = get_sphere('repulsion724').subdivide(1)

random.seed(5)

for i in range(15):
    
    random_number = random.randint(0, len(F_pred_np))
    _, peak_count = detect_peaks(F_pred_np[random_number].reshape(1,-1), 0.5, 25)
    gt_peak_count = np.count_nonzero(gt_white_masked[random_number]) / 3
    odf = multi_tensor_odf(sphere2.vertices, evals, angles=angle_pairs,
                              fractions=F_pred_np[random_number])
    
    gt_angles, gt_fractions = angles_fractions(gt_white_masked[random_number])
    odf_gt = multi_tensor_odf(sphere2.vertices, evals, angles=gt_angles,
                              fractions=gt_fractions)
    
    from dipy.viz import window, actor
    
    # Enables/disables interactive visualization
    interactive = False
    
    
    scene = window.Scene()
    
    odfs = np.vstack((odf, odf_gt))[:, None, None]
    odf_actor = actor.odf_slicer(odfs, sphere=sphere2, scale=0.5, colormap='plasma')
    
    odf_actor.display(y=0)
    odf_actor.RotateX(90)
    scene.add(odf_actor)
    window.record(scene, out_path='trained_model/hardi_results/threshold_3_res_' + str(random_number) + 'peak_count_' + str(peak_count) + '_gt_peak_count_' + str(gt_peak_count) + '.png', size=(300, 300))
    if interactive:
        window.show(scene)

In [ ]:
gt_angles

In [ ]:
random_number

In [ ]:
hardi_snr30_white_masked[849]

In [ ]:
with open('real_data/hardi-scheme.bvec.txt', 'r') as file:
    lines = file.readlines()
real_bvecs = []
for line in lines:
    values = line.split()
    real_bvecs.append([float(value) for value in values])
real_bvecs = np.array(real_bvecs).T


with open('real_data/hardi-scheme.bval.txt', 'r') as file:
    lines = file.readlines()

real_bvals = []
for line in lines:
    values = line.split()
    real_bvals.append([float(value) for value in values])

real_bvals = np.array(real_bvals).reshape(-1)

gtab = gradient_table(real_bvals, real_bvecs)

In [ ]:
d_parallel = 0.0015
d_perp = 0.00039
eigenvals = [d_parallel, d_perp, d_perp]
a = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=30)[0]

In [35]:
import matplotlib.pyplot as plt

plt.plot(a)
plt.plot(hardi_snr30_white_masked[849])

array([[105.80883414,  18.47758824,  15.42564515, ...,  11.44683225,
         25.84922221,  20.60763734],
       [ 99.58721804,  19.13866153,  20.49738568, ...,  19.29782281,
         10.33689156,  16.57899893],
       [100.        ,   6.74715108,  15.97139409, ...,  19.96619745,
         15.99120786,  25.95446839],
       ...,
       [110.1815024 ,   6.80477209,   6.23242756, ...,  13.85581028,
         21.89885241,  28.2759651 ],
       [102.18475096,  16.69135328,   7.81423082, ...,   2.66162189,
         11.14373645,   7.7727093 ],
       [ 99.79075947,  24.29025214,  19.6397756 , ...,  29.3103679 ,
         19.1689361 ,  27.5113017 ]])

In [51]:
a_20 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=20)[0]
plt.plot(a_20)
plt.plot(hardi_snr20_white_masked[849])

In [52]:
a_10 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=10)[0]
plt.plot(a_10)
plt.plot(hardi_snr10_white_masked[849])

array([[105.80883414,  18.47758824,  15.42564515, ...,  11.44683225,
         25.84922221,  20.60763734],
       [ 99.58721804,  19.13866153,  20.49738568, ...,  19.29782281,
         10.33689156,  16.57899893],
       [100.        ,   6.74715108,  15.97139409, ...,  19.96619745,
         15.99120786,  25.95446839],
       ...,
       [110.1815024 ,   6.80477209,   6.23242756, ...,  13.85581028,
         21.89885241,  28.2759651 ],
       [102.18475096,  16.69135328,   7.81423082, ...,   2.66162189,
         11.14373645,   7.7727093 ],
       [ 99.79075947,  24.29025214,  19.6397756 , ...,  29.3103679 ,
         19.1689361 ,  27.5113017 ]])

In [ ]:
a_10 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=10)[0]
plt.plot(a_10)
a_15 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=15)[0]
plt.plot(a_10)
a_20 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=20)[0]
plt.plot(a_10)
a_25 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=25)[0]
plt.plot(a_10)
a_30 = multi_tensor(gtab, mevals = [eigenvals], S0=100, angles=gt_angles, fractions=[100], snr=30)[0]
plt.plot(a_10)

plt.plot(a_10)
plt.plot(a_15)
plt.plot(a_20)
plt.plot(a_25)
plt.plot(a_30)
plt.plot(hardi_snr30_white_masked[849], linewidth = 3.0, color = 'red')

In [2]:
S = np.load("synthetic_data/tugbanindahiyanefikri_custom/S.npy")
F = np.load("synthetic_data/tugbanindahiyanefikri_custom/F.npy")

In [3]:
import random

# Combine into pairs
combined_data = list(zip(S, F))

# Shuffle the pairs
random.shuffle(combined_data)

# Unzip back into separate arrays
S, F = zip(*combined_data)


In [4]:
np.save("synthetic_data/tugbanindahiyanefikri_custom/S.npy", S)
np.save("synthetic_data/tugbanindahiyanefikri_custom/F.npy", F)

In [5]:
np.array(S)

array([[105.80883414,  18.47758824,  15.42564515, ...,  11.44683225,
         25.84922221,  20.60763734],
       [ 99.58721804,  19.13866153,  20.49738568, ...,  19.29782281,
         10.33689156,  16.57899893],
       [100.        ,   6.74715108,  15.97139409, ...,  19.96619745,
         15.99120786,  25.95446839],
       ...,
       [110.1815024 ,   6.80477209,   6.23242756, ...,  13.85581028,
         21.89885241,  28.2759651 ],
       [102.18475096,  16.69135328,   7.81423082, ...,   2.66162189,
         11.14373645,   7.7727093 ],
       [ 99.79075947,  24.29025214,  19.6397756 , ...,  29.3103679 ,
         19.1689361 ,  27.5113017 ]])

In [6]:
np.array(F)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [155]:
gt_peaks = pd.read_pickle("real_data/ground_truth_peaks_white_masked.pkl")

In [156]:
# Calculate the number of columns to add on each side
columns_to_add = 42 - gt_peaks.shape[1]

# Pad the matrix with zeros
padded_matrix = np.pad(gt_peaks, ((0, 0), (0, columns_to_add)), mode='constant', constant_values=0)

In [158]:
padded_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [159]:
pd.to_pickle(padded_matrix, "real_data/ground_truth_peaks_padded.pkl")